package com.github.paohaijiao.ele;

import com.github.paohaijiao.JOption;
import com.github.paohaijiao.adaptor.JAdaptor;
import com.github.paohaijiao.axis.JCategoryAxis;
import com.github.paohaijiao.axis.JValueAxis;
import com.github.paohaijiao.code.JTrigger;
import com.github.paohaijiao.config.JGraphConfig;
import com.github.paohaijiao.config.JPdfConfig;
import com.github.paohaijiao.config.JTemplateConfig;
import com.github.paohaijiao.config.JTreeNodeConfig;
import com.github.paohaijiao.data.JGraphContainer;
import com.github.paohaijiao.enums.JChartType;
import com.github.paohaijiao.executor.JQuickPdfXExecutor;
import com.github.paohaijiao.extension.tree.TreeNode;
import com.github.paohaijiao.param.JContext;
import com.github.paohaijiao.resouce.JReader;
import com.github.paohaijiao.resouce.impl.JReSourceFileReader;
import com.github.paohaijiao.series.JCandlestick;
import org.junit.Test;

import java.io.IOException;

public class JElementTest {

    @Test
    public void paragraph() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/paragraph.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void heading() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/heading.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void list() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/list.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void table() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/table.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void image() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/image.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void svg1() throws IOException {
        JContext params = new JContext();
        String svg = "<?xml version=\"1.0\"?>\n" +
                "<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.0//EN'\n" +
                "          'http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd'>\n" +
                "<svg xmlns:xlink=\"http://www.w3.org/1999/xlink\" style=\"fill-opacity:1; color-rendering:auto; color-interpolation:auto; text-rendering:auto; stroke:black; stroke-linecap:square; stroke-miterlimit:10; shape-rendering:auto; stroke-opacity:1; fill:black; stroke-dasharray:none; font-weight:normal; stroke-width:1; font-family:'Dialog'; font-style:normal; stroke-linejoin:miter; font-size:12px; stroke-dashoffset:0; image-rendering:auto;\" width=\"800\" height=\"600\" xmlns=\"http://www.w3.org/2000/svg\"\n" +
                "><!--Generated by the Batik Graphics2D SVG Generator--><defs id=\"genericDefs\"\n" +
                "  /><g\n" +
                "  ><g style=\"fill:white; stroke:white;\"\n" +
                "    ><rect x=\"0\" width=\"800\" height=\"600\" y=\"0\" style=\"stroke:none;\"\n" +
                "    /></g\n" +
                "    ><g style=\"font-family:'微软雅黑'; font-size:18px; font-weight:bold;\"\n" +
                "    ><text x=\"364\" xml:space=\"preserve\" y=\"40\" style=\"stroke:none;\"\n" +
                "      >销售数据</text\n" +
                "      ><text x=\"374\" y=\"60\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >2023年度</text\n" +
                "      ><line y2=\"540\" style=\"fill:none;\" x1=\"60\" x2=\"740\" y1=\"540\"\n" +
                "      /><line y2=\"60\" style=\"fill:none;\" x1=\"60\" x2=\"60\" y1=\"540\"\n" +
                "      /><text x=\"175\" y=\"560\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >衬衫</text\n" +
                "      ><text x=\"254\" y=\"560\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >羊毛衫</text\n" +
                "      ><text x=\"339\" y=\"560\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >雪纺衫</text\n" +
                "      ><text x=\"430\" y=\"560\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >裤子</text\n" +
                "      ><text x=\"509\" y=\"560\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >高跟鞋</text\n" +
                "      ><text x=\"600\" y=\"560\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >袜子</text\n" +
                "      ><text x=\"30\" y=\"545\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >0</text\n" +
                "      ><line y2=\"540\" style=\"fill:none;\" x1=\"55\" x2=\"60\" y1=\"540\"\n" +
                "      /><text x=\"30\" y=\"452\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >7</text\n" +
                "      ><line y2=\"447\" style=\"fill:none;\" x1=\"55\" x2=\"60\" y1=\"447\"\n" +
                "      /><text x=\"30\" y=\"359\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >14</text\n" +
                "      ><line y2=\"354\" style=\"fill:none;\" x1=\"55\" x2=\"60\" y1=\"354\"\n" +
                "      /><text x=\"30\" y=\"265\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >21</text\n" +
                "      ><line y2=\"260\" style=\"fill:none;\" x1=\"55\" x2=\"60\" y1=\"260\"\n" +
                "      /><text x=\"30\" y=\"172\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >28</text\n" +
                "      ><line y2=\"167\" style=\"fill:none;\" x1=\"55\" x2=\"60\" y1=\"167\"\n" +
                "      /><text x=\"30\" y=\"79\" style=\"font-size:12px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
                "      >35</text\n" +
                "      ><line y2=\"74\" style=\"fill:none;\" x1=\"55\" x2=\"60\" y1=\"74\"\n" +
                "    /></g\n" +
                "    ><g style=\"fill:rgb(65,105,225); font-family:'微软雅黑'; stroke:rgb(65,105,225);\"\n" +
                "    ><rect x=\"145\" width=\"80\" height=\"66\" y=\"474\" style=\"stroke:none;\"\n" +
                "      /><text x=\"184\" xml:space=\"preserve\" y=\"469\" style=\"fill:black; stroke:none;\"\n" +
                "      >5</text\n" +
                "      ><rect x=\"230\" width=\"80\" height=\"266\" y=\"274\" style=\"stroke:none;\"\n" +
                "      /><text x=\"265\" xml:space=\"preserve\" y=\"269\" style=\"fill:black; stroke:none;\"\n" +
                "      >20</text\n" +
                "      ><rect x=\"315\" width=\"80\" height=\"480\" y=\"60\" style=\"stroke:none;\"\n" +
                "      /><text x=\"350\" xml:space=\"preserve\" y=\"55\" style=\"fill:black; stroke:none;\"\n" +
                "      >36</text\n" +
                "      ><rect x=\"400\" width=\"80\" height=\"133\" y=\"407\" style=\"stroke:none;\"\n" +
                "      /><text x=\"435\" xml:space=\"preserve\" y=\"402\" style=\"fill:black; stroke:none;\"\n" +
                "      >10</text\n" +
                "      ><rect x=\"485\" width=\"80\" height=\"133\" y=\"407\" style=\"stroke:none;\"\n" +
                "      /><text x=\"520\" xml:space=\"preserve\" y=\"402\" style=\"fill:black; stroke:none;\"\n" +
                "      >10</text\n" +
                "      ><rect x=\"570\" width=\"80\" height=\"266\" y=\"274\" style=\"stroke:none;\"\n" +
                "      /><text x=\"605\" xml:space=\"preserve\" y=\"269\" style=\"fill:black; stroke:none;\"\n" +
                "      >20</text\n" +
                "    ></g\n" +
                "  ></g\n" +
                "></svg>";
        params.put("svg", svg);
        JReader fileReader = new JReSourceFileReader("sample/svg1.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor(params);
        executor.execute(context.getRuleContent());
    }
    @Test
    public void svg2() throws IOException {
        JGraphContainer graphContainer=new JGraphContainer();
        JOption option = new JOption();
        option.title().text("股票K线图(含数据)");
        option.tooltip().trigger(JTrigger.axis);
        JCategoryAxis xAxis = new JCategoryAxis();
        xAxis.data("01/01", "01/02", "01/03", "01/04", "01/05",
                "01/06", "01/07", "01/08", "01/09", "01/10");
        option.xAxis(xAxis);
        option.yAxis(new JValueAxis());
        JCandlestick candlestick = new JCandlestick();
        candlestick.name("股价")
                .data(
                        new Object[]{105.2, 108.5, 104.8, 109.1},
                        new Object[]{108.6, 107.8, 106.5, 109.5},
                        new Object[]{107.9, 105.3, 104.2, 108.0},
                        new Object[]{105.4, 106.1, 104.5, 107.2},
                        new Object[]{106.2, 104.8, 103.0, 107.5},
                        new Object[]{104.9, 107.3, 104.0, 108.2},
                        new Object[]{107.4, 109.1, 106.5, 110.2},
                        new Object[]{109.2, 108.8, 107.0, 110.5},
                        new Object[]{108.9, 110.3, 108.2, 111.0},
                        new Object[]{110.4, 112.1, 109.5, 112.8}
                );
        option.series(candlestick);
        graphContainer.setOption(option);
        graphContainer.setType(JChartType.K);
        JGraphConfig graphConfig=new JGraphConfig();
        graphConfig.put("svg",graphContainer);

        JPdfConfig config = new JPdfConfig();
        config.setGraphConfig(graphConfig);
        JReader fileReader = new JReSourceFileReader("sample/svg2.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor(config);
        executor.execute(context.getRuleContent());
    }
    @Test
    public void div() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/div.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void span() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/span.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void areaBreak() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/areaBreak.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void button() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/button.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void checkbox() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/checkbox.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void comboxFiled() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/comboxFiled.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void htmlPageBreak() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/htmlPageBreak.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void inputField() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/inputField.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void lineSeperator() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/lineSeperator.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void link() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/link.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void listBoxField() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/listBoxField.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void pageCountElement() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/pageCountElem.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void tab() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/tab.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void textArea() throws IOException {
        JReader fileReader = new JReSourceFileReader("sample/textArea.txt");
        JAdaptor context = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor();
        executor.execute(context.getRuleContent());
    }
    @Test
    public void tree1() throws IOException {
        JContext context=new JContext();
        TreeNode root = new TreeNode("Root");
        TreeNode child1 = new TreeNode("Documents");
        TreeNode child2 = new TreeNode("Images");
        TreeNode child3 = new TreeNode("System");
        child3.setSelected(true);
        root.addChild(child1);
        root.addChild(child2);
        root.addChild(child3);
        context.put("tree", root);
        JReader fileReader = new JReSourceFileReader("sample/tree1.txt");
        JAdaptor adaptor = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor(context);
        executor.execute(adaptor.getRuleContent());
    }
    @Test
    public void tree2() throws IOException {
        JPdfConfig config=new JPdfConfig();
        TreeNode root = new TreeNode("Root");
        TreeNode child1 = new TreeNode("Documents");
        TreeNode child2 = new TreeNode("Images");
        TreeNode child3 = new TreeNode("System");
        child3.setSelected(true);
        root.addChild(child1);
        root.addChild(child2);
        root.addChild(child3);
        JTreeNodeConfig treeNodeConfig=config.getTreeConfig();
        treeNodeConfig.put("tree", root);
        JReader fileReader = new JReSourceFileReader("sample/tree2.txt");
        JAdaptor adaptor = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor(config);
        executor.execute(adaptor.getRuleContent());
    }
    @Test
    public void template() throws IOException {
        JPdfConfig config=new JPdfConfig();
        JTemplateConfig templateConfig=config.getTemplateConfig();
        templateConfig.put("html", "<h1>Hello World</h1><p>This is a test PDF generated from HTML</p>");
        JReader fileReader = new JReSourceFileReader("sample/template.txt");
        JAdaptor adaptor = new JAdaptor(fileReader);
        JQuickPdfXExecutor executor = new JQuickPdfXExecutor(config);
        executor.execute(adaptor.getRuleContent());
    }




}
