package com.github.paohaijiao.element.special;

import com.github.paohaijiao.JOption;
import com.github.paohaijiao.axis.JCategoryAxis;
import com.github.paohaijiao.axis.JValueAxis;
import com.github.paohaijiao.code.JTrigger;
import com.github.paohaijiao.config.JGraphConfig;
import com.github.paohaijiao.config.JPdfConfig;
import com.github.paohaijiao.data.JGraphContainer;
import com.github.paohaijiao.demo.constant.JQuickConstant;
import com.github.paohaijiao.enums.JChartType;
import com.github.paohaijiao.executor.JQuickPdfFactory;
import com.github.paohaijiao.extension.tree.TreeNode;
import com.github.paohaijiao.series.JCandlestick;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.contentstream.operator.Operator;
import org.apache.pdfbox.cos.COSBase;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.cos.COSNumber;
import org.apache.pdfbox.pdfparser.PDFStreamParser;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDResources;
import org.apache.pdfbox.pdmodel.graphics.PDXObject;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.pdfbox.text.TextPosition;
import org.junit.Test;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * 特殊元素的单元用例：{@code <image>} 嵌入图片、{@code <svg>} 矢量图形、
 * {@code <tree>} 树形结构数据，以及 {@code ${variable}} 数据绑定占位符。
 * <p>
 * 每个用例渲染 {@code src/test/resources/sample/special} 下的模板（写法与 README 的特殊元素表一致），
 * 再从生成的 PDF 中提取文本、内容流算子与图片绘制矩阵，验证元素确实按文档语义绘制：
 * 图片尺寸按 px→pt 换算、SVG 按自身宽高栅格化并嵌入、树节点带缩进与连接线、占位符被真实数据替换。
 * <p>
 * 说明：文档中 {@code <tree>tree</tree>} 这种裸写名称的形式在当前解析器语法中并没有对应规则
 * （{@code tree} 规则只接受 {@code ${x}} 变量与 {@code &{x}} 引用），解析时该文本会被丢弃并产出空白页，
 * 因此这里覆盖 {@code <tree>${tree}</tree>} 与 {@code <tree>&{tree}</tree>} 两种受支持的写法。
 */
public class JSpecialElementTest {

    public static final String  path= JQuickConstant.path;

    /** 宽高声明为 120×60 的最小 SVG，用于验证 {@code <svg>} 按自身尺寸栅格化后嵌入。 */
    private static final String SVG = "<?xml version=\"1.0\"?>\n" +
            "<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.0//EN'\n" +
            "          'http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd'>\n" +
            "<svg xmlns:xlink=\"http://www.w3.org/1999/xlink\" style=\"fill-opacity:1; color-rendering:auto; color-interpolation:auto; text-rendering:auto; stroke:black; stroke-linecap:square; stroke-miterlimit:10; shape-rendering:auto; stroke-opacity:1; fill:black; stroke-dasharray:none; font-weight:normal; stroke-width:1; font-family:'Dialog'; font-style:normal; stroke-linejoin:miter; font-size:12px; stroke-dashoffset:0; image-rendering:auto;\" width=\"800\" height=\"600\" xmlns=\"http://www.w3.org/2000/svg\"\n" +
            "><!--Generated by the Batik Graphics2D SVG Generator--><defs id=\"genericDefs\"\n" +
            "  /><g\n" +
            "  ><defs id=\"defs1\"\n" +
            "    ><linearGradient x1=\"0\" gradientUnits=\"userSpaceOnUse\" x2=\"0\" y1=\"60\" y2=\"430\" id=\"linearGradient1\" spreadMethod=\"pad\"\n" +
            "      ><stop style=\"stop-opacity:0.7843; stop-color:rgb(255,158,68);\" offset=\"0%\"\n" +
            "        /><stop style=\"stop-opacity:0.3922; stop-color:rgb(255,70,131);\" offset=\"100%\"\n" +
            "      /></linearGradient\n" +
            "    ></defs\n" +
            "    ><g style=\"fill:white; stroke:white;\"\n" +
            "    ><rect x=\"0\" width=\"800\" height=\"600\" y=\"0\" style=\"stroke:none;\"\n" +
            "      /><rect x=\"0\" y=\"0\" width=\"800\" style=\"fill:rgb(249,249,249); stroke:none;\" rx=\"4\" ry=\"4\" height=\"500\"\n" +
            "      /><line x1=\"60\" x2=\"760\" y1=\"430\" style=\"fill:none; stroke:rgb(221,221,221);\" y2=\"430\"\n" +
            "      /><text x=\"28\" y=\"435\" style=\"fill:rgb(136,136,136); font-family:'微软雅黑'; stroke:none;\" xml:space=\"preserve\"\n" +
            "      >41.5</text\n" +
            "    ></g\n" +
            "    ><g style=\"stroke-linecap:butt; fill:rgb(221,221,221); font-family:'微软雅黑'; stroke-linejoin:bevel; stroke-dasharray:4,4; stroke:rgb(221,221,221); stroke-miterlimit:0;\"\n" +
            "    ><line y2=\"369\" style=\"fill:none;\" x1=\"60\" x2=\"760\" y1=\"369\"\n" +
            "    /></g\n" +
            "    ><g style=\"fill:rgb(136,136,136); font-family:'微软雅黑'; stroke:rgb(136,136,136);\"\n" +
            "    ><text x=\"21\" xml:space=\"preserve\" y=\"374\" style=\"stroke:none;\"\n" +
            "      >128.5</text\n" +
            "    ></g\n" +
            "    ><g style=\"stroke-linecap:butt; fill:rgb(221,221,221); font-family:'微软雅黑'; stroke-linejoin:bevel; stroke-dasharray:4,4; stroke:rgb(221,221,221); stroke-miterlimit:0;\"\n" +
            "    ><line y2=\"307\" style=\"fill:none;\" x1=\"60\" x2=\"760\" y1=\"307\"\n" +
            "    /></g\n" +
            "    ><g style=\"fill:rgb(136,136,136); font-family:'微软雅黑'; stroke:rgb(136,136,136);\"\n" +
            "    ><text x=\"21\" xml:space=\"preserve\" y=\"312\" style=\"stroke:none;\"\n" +
            "      >215.5</text\n" +
            "    ></g\n" +
            "    ><g style=\"stroke-linecap:butt; fill:rgb(221,221,221); font-family:'微软雅黑'; stroke-linejoin:bevel; stroke-dasharray:4,4; stroke:rgb(221,221,221); stroke-miterlimit:0;\"\n" +
            "    ><line y2=\"245\" style=\"fill:none;\" x1=\"60\" x2=\"760\" y1=\"245\"\n" +
            "    /></g\n" +
            "    ><g style=\"fill:rgb(136,136,136); font-family:'微软雅黑'; stroke:rgb(136,136,136);\"\n" +
            "    ><text x=\"21\" xml:space=\"preserve\" y=\"250\" style=\"stroke:none;\"\n" +
            "      >302.5</text\n" +
            "    ></g\n" +
            "    ><g style=\"stroke-linecap:butt; fill:rgb(221,221,221); font-family:'微软雅黑'; stroke-linejoin:bevel; stroke-dasharray:4,4; stroke:rgb(221,221,221); stroke-miterlimit:0;\"\n" +
            "    ><line y2=\"184\" style=\"fill:none;\" x1=\"60\" x2=\"760\" y1=\"184\"\n" +
            "    /></g\n" +
            "    ><g style=\"fill:rgb(136,136,136); font-family:'微软雅黑'; stroke:rgb(136,136,136);\"\n" +
            "    ><text x=\"21\" xml:space=\"preserve\" y=\"189\" style=\"stroke:none;\"\n" +
            "      >389.5</text\n" +
            "    ></g\n" +
            "    ><g style=\"stroke-linecap:butt; fill:rgb(221,221,221); font-family:'微软雅黑'; stroke-linejoin:bevel; stroke-dasharray:4,4; stroke:rgb(221,221,221); stroke-miterlimit:0;\"\n" +
            "    ><line y2=\"122\" style=\"fill:none;\" x1=\"60\" x2=\"760\" y1=\"122\"\n" +
            "    /></g\n" +
            "    ><g style=\"fill:rgb(136,136,136); font-family:'微软雅黑'; stroke:rgb(136,136,136);\"\n" +
            "    ><text x=\"21\" xml:space=\"preserve\" y=\"127\" style=\"stroke:none;\"\n" +
            "      >476.5</text\n" +
            "      ><line x1=\"60\" x2=\"760\" y1=\"60\" style=\"fill:none; stroke:rgb(221,221,221);\" y2=\"60\"\n" +
            "      /><text x=\"21\" xml:space=\"preserve\" y=\"65\" style=\"stroke:none;\"\n" +
            "      >563.5</text\n" +
            "      ><line x1=\"60\" x2=\"60\" y1=\"60\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"430\"\n" +
            "      /><line x1=\"60\" x2=\"760\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"430\"\n" +
            "      /><path d=\"M60 399.1667 L123.6364 374.3582 L187.2727 353.0939 L250.9091 310.5651 L314.5454 260.9483 L378.1818 211.3314 L441.8182 161.7146 L505.4546 175.8908 L569.0909 190.067 L632.7273 140.4502 L696.3636 119.1858 L760 90.8333 L760 430 L60 430 Z\" style=\"fill:url(#linearGradient1); stroke:none;\"\n" +
            "    /></g\n" +
            "    ><g style=\"fill:rgb(255,70,131); stroke-width:2.5; font-family:'微软雅黑'; stroke-linecap:round; stroke:rgb(255,70,131); stroke-linejoin:round;\"\n" +
            "    ><path style=\"fill:none;\" d=\"M60 399.1667 L123.6364 374.3582 L187.2727 353.0939 L250.9091 310.5651 L314.5454 260.9483 L378.1818 211.3314 L441.8182 161.7146 L505.4546 175.8908 L569.0909 190.067 L632.7273 140.4502 L696.3636 119.1858 L760 90.8333\"\n" +
            "      /><text x=\"62\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >1月</text\n" +
            "      ><text x=\"114\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >2月</text\n" +
            "      ><text x=\"178\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >3月</text\n" +
            "      ><text x=\"241\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >4月</text\n" +
            "      ><text x=\"305\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >5月</text\n" +
            "      ><text x=\"369\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >6月</text\n" +
            "      ><text x=\"432\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >7月</text\n" +
            "      ><text x=\"496\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >8月</text\n" +
            "      ><text x=\"560\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >9月</text\n" +
            "      ><text x=\"619\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >10月</text\n" +
            "      ><text x=\"683\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >11月</text\n" +
            "      ><text x=\"732\" xml:space=\"preserve\" y=\"450\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >12月</text\n" +
            "      ><line x1=\"60\" x2=\"60\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"123\" x2=\"123\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"187\" x2=\"187\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"250\" x2=\"250\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"314\" x2=\"314\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"378\" x2=\"378\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"441\" x2=\"441\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"505\" x2=\"505\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"569\" x2=\"569\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"632\" x2=\"632\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"696\" x2=\"696\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><line x1=\"760\" x2=\"760\" y1=\"430\" style=\"fill:none; stroke:rgb(102,102,102);\" y2=\"435\"\n" +
            "      /><text x=\"398\" xml:space=\"preserve\" y=\"475\" style=\"fill:rgb(51,51,51); stroke:none;\"\n" +
            "      >月份</text\n" +
            "      ><text x=\"-42\" y=\"0\" transform=\"translate(25,245) rotate(-90)\" style=\"fill:rgb(51,51,51); stroke:none;\" xml:space=\"preserve\"\n" +
            "      >销售额（万元）</text\n" +
            "    ></g\n" +
            "    ><g style=\"stroke-linecap:round; font-size:18px; fill:rgb(51,51,51); font-family:'微软雅黑'; stroke-linejoin:round; stroke:rgb(51,51,51); font-weight:bold; stroke-width:2.5;\"\n" +
            "    ><text x=\"324\" xml:space=\"preserve\" y=\"35\" style=\"stroke:none;\"\n" +
            "      >2024年度销售趋势</text\n" +
            "      ><text x=\"337\" y=\"58\" style=\"font-size:14px; font-weight:normal; stroke:none;\" xml:space=\"preserve\"\n" +
            "      >数据来源：销售系统</text\n" +
            "    ></g\n" +
            "    ><g style=\"stroke-linecap:round; font-size:14px; fill:rgb(255,70,131); font-family:'微软雅黑'; stroke-linejoin:round; stroke:rgb(255,70,131); stroke-width:2.5;\"\n" +
            "    ><rect x=\"340\" y=\"477\" width=\"18\" style=\"stroke:none;\" rx=\"1.5\" ry=\"1.5\" height=\"18\"\n" +
            "      /><text x=\"366\" y=\"495\" style=\"fill:rgb(51,51,51); font-size:12px; stroke:none;\" xml:space=\"preserve\"\n" +
            "      >销售额</text\n" +
            "      ><text x=\"54\" xml:space=\"preserve\" y=\"391\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >85</text\n" +
            "      ><text x=\"114\" xml:space=\"preserve\" y=\"366\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >120</text\n" +
            "      ><text x=\"178\" xml:space=\"preserve\" y=\"345\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >150</text\n" +
            "      ><text x=\"241\" xml:space=\"preserve\" y=\"302\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >210</text\n" +
            "      ><text x=\"305\" xml:space=\"preserve\" y=\"252\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >280</text\n" +
            "      ><text x=\"369\" xml:space=\"preserve\" y=\"203\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >350</text\n" +
            "      ><text x=\"432\" xml:space=\"preserve\" y=\"153\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >420</text\n" +
            "      ><text x=\"496\" xml:space=\"preserve\" y=\"167\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >400</text\n" +
            "      ><text x=\"560\" xml:space=\"preserve\" y=\"182\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >380</text\n" +
            "      ><text x=\"623\" xml:space=\"preserve\" y=\"132\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >450</text\n" +
            "      ><text x=\"687\" xml:space=\"preserve\" y=\"111\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >480</text\n" +
            "      ><text x=\"751\" xml:space=\"preserve\" y=\"82\" style=\"font-size:11px; stroke:none;\"\n" +
            "      >520</text\n" +
            "    ></g\n" +
            "  ></g\n" +
            "></svg\n" +
            ">\n";

    /** 嵌入图片：本地图片按声明宽高绘制，{@code px} 需按 CSS 96dpi 换算为 pt（200px=150pt、150px=112.5pt）。 */
    @Test
    public void image() throws IOException {
        Rendered rendered = render(new JQuickPdfFactory(), "sample/special/image.txt");
        assertEquals(1, rendered.pages);
        assertEquals("应嵌入 1 张图片", 1, rendered.images.size());
        assertEquals("图片应被绘制一次", 1, rendered.operatorCount("Do"));
        assertEquals("嵌入的图片应保留原始像素宽度", 2481, rendered.imageWidth(0));
        assertEquals("嵌入的图片应保留原始像素高度", 3509, rendered.imageHeight(0));
        float[] matrix = rendered.drawMatrix(0);
        assertEquals("width:200px 应换算为 150pt", 150f, matrix[0], 0.5f);
        assertEquals("height:150px 应换算为 112.5pt", 112.5f, matrix[3], 0.5f);
    }

    /** 矢量图形：{@code ${svg}} 绑定 SVG 字符串，按 SVG 自身宽高（120×60）栅格化后作为图片嵌入。 */
    @Test
    public void svg() throws IOException {
        Rendered rendered = render(new JQuickPdfFactory().bind("svg", SVG), "sample/special/svg.txt");
        assertEquals(1, rendered.pages);
        assertEquals("SVG 应作为 1 张图片嵌入", 1, rendered.images.size());
        assertEquals("SVG 应被绘制一次", 1, rendered.operatorCount("Do"));
        float[] matrix = rendered.drawMatrix(0);
        assertEquals("SVG 应按自身宽度 120pt 绘制", 523f, matrix[0], 0.5f);
        assertEquals("SVG 应按自身高度 60pt 绘制", 392f, matrix[3], 0.5f);
        assertEquals("SVG 应按 300dpi 栅格化（120pt→500px）", 2180, rendered.imageWidth(0));
        assertEquals("SVG 应按 300dpi 栅格化（60pt→250px）", 1635, rendered.imageHeight(0));
    }

    /** 矢量图形：{@code &{svg}} 走图表配置，图表渲染出的 SVG 同样被栅格化嵌入且不超出页面宽度。 */
    @Test
    public void svgByAddress() throws IOException {
        Rendered rendered = render(graphFactory(), "sample/special/svgAddress.txt");
        assertEquals(1, rendered.pages);
        assertEquals("图表 SVG 应作为 1 张图片嵌入", 1, rendered.images.size());
        assertEquals("图表 SVG 应被绘制一次", 1, rendered.operatorCount("Do"));
        float[] matrix = rendered.drawMatrix(0);
        assertTrue("图表应具有正的绘制宽度", matrix[0] > 0f);
        assertTrue("图表应具有正的绘制高度", matrix[3] > 0f);
        assertTrue("图表宽度不应超出页面宽度", matrix[0] <= rendered.pageWidth);
        float imageRatio = rendered.imageWidth(0) / (float) rendered.imageHeight(0);
        assertEquals("图表应按原始比例绘制，不得拉伸变形", imageRatio, matrix[0] / matrix[3], 0.02f);
    }

    /** 树形结构：{@code ${tree}} 绑定 TreeNode，子节点缩进绘制在父节点右下方，并绘制节点背景与层级连接线。 */
    @Test
    public void tree() throws IOException {
        Rendered rendered = render(new JQuickPdfFactory().bind("tree", treeData()), "sample/special/tree.txt");
        assertTreeLayout(rendered);
    }

    /** 树形结构：{@code &{tree}} 走树配置解析，渲染结果与 {@code ${tree}} 变量绑定一致。 */
    @Test
    public void treeByAddress() throws IOException {
        Rendered rendered = render(treeFactory(), "sample/special/treeAddress.txt");
        assertTreeLayout(rendered);
    }

    /** 数据绑定占位符：{@code ${name}} 被绑定值替换，且不会把占位符原样输出。 */
    @Test
    public void variable() throws IOException {
        Rendered rendered = render(new JQuickPdfFactory().bind("name", "张三"), "sample/special/variable.txt");
        assertEquals(1, rendered.pages);
        assertEquals("占位符应被绑定值替换", "姓名: 张三", rendered.text());
        assertFalse("占位符不应被原样输出", rendered.text().contains("${"));
    }

    /** 校验树节点确实按层级排版：文本、缩进、上下顺序、节点背景框与连接线。 */
    private void assertTreeLayout(Rendered rendered) {
        assertEquals(1, rendered.pages);
        Glyph root = rendered.glyph("根节点");
        Glyph child = rendered.glyph("子节点");
        assertTrue("子节点应缩进绘制在根节点右侧", child.x > root.x);
        assertTrue("子节点应绘制在根节点下方", child.y > root.y);
        assertTrue("每个节点应绘制背景框", rendered.rectCount() >= 2);
        assertTrue("应绘制层级连接线", rendered.operatorCount("l") >= 2);
    }

    /** 两组节点的树：根节点 + 一个子节点。 */
    private TreeNode treeData() {
        TreeNode root = new TreeNode("根节点");
        root.addChild(new TreeNode("子节点"));
        return root;
    }

    /** 带 {@code &{tree}} 树配置的工厂。 */
    private JQuickPdfFactory treeFactory() {
        JPdfConfig config = new JPdfConfig();
        config.getTreeConfig().put("tree", treeData());
        return new JQuickPdfFactory(config);
    }

    /** 带 {@code &{svg}} 图表配置的工厂，图表类型为 K 线图。 */
    private JQuickPdfFactory graphFactory() {
        JGraphContainer graphContainer = new JGraphContainer();
        JOption option = new JOption();
        option.title().text("股票K线图");
        option.tooltip().trigger(JTrigger.axis);
        JCategoryAxis xAxis = new JCategoryAxis();
        xAxis.data("01/01", "01/02", "01/03");
        option.xAxis(xAxis);
        option.yAxis(new JValueAxis());
        JCandlestick candlestick = new JCandlestick();
        candlestick.name("股价").data(new Object[]{105.2, 108.5, 104.8, 109.1},
                new Object[]{108.6, 107.8, 106.5, 109.5}, new Object[]{107.9, 105.3, 104.2, 108.0});
        option.series(candlestick);
        graphContainer.setOption(option);
        graphContainer.setType(JChartType.K);
        JGraphConfig graphConfig = new JGraphConfig();
        graphConfig.put("svg", graphContainer);
        JPdfConfig config = new JPdfConfig();
        config.setGraphConfig(graphConfig);
        return new JQuickPdfFactory(config);
    }

    /** 渲染模板并提取文本坐标、页数、内容流算子、矩形外框、嵌入图片与图片绘制矩阵。 */
    private Rendered render(JQuickPdfFactory factory, String resource) throws IOException {
        byte[] pdf = factory.executeResource(resource);
        List<Glyph> glyphs = new ArrayList<>();
        Map<String, Integer> operators = new HashMap<>();
        List<float[]> boxes = new ArrayList<>();
        List<float[]> images = new ArrayList<>();
        List<float[]> drawMatrices = new ArrayList<>();
        int pages;
        float pageWidth;
        try (PDDocument document = Loader.loadPDF(pdf)) {
            pages = document.getNumberOfPages();
            pageWidth = document.getPage(0).getMediaBox().getWidth();
            PDFTextStripper stripper = new PDFTextStripper() {
                @Override
                protected void writeString(String text, List<TextPosition> positions) {
                    if (positions == null || positions.isEmpty() || text == null || text.trim().isEmpty()) {
                        return;
                    }
                    TextPosition first = positions.get(0);
                    glyphs.add(new Glyph(text.trim(), first.getXDirAdj(), first.getYDirAdj()));
                }
            };
            stripper.setSortByPosition(true);
            stripper.getText(document);
            for (PDPage page : document.getPages()) {
                collectImages(page, images);
                collect(page, operators, boxes, drawMatrices);
            }
        }
        FileOutputStream fileOutputStream = new FileOutputStream(path+"test.pdf");
        fileOutputStream.write(pdf);
        return new Rendered(pages, pageWidth, glyphs, operators, boxes, images, drawMatrices);
    }

    /** 收集页面资源中的位图，记录其像素尺寸（{@code [width, height]}）。 */
    private void collectImages(PDPage page, List<float[]> images) throws IOException {
        PDResources resources = page.getResources();
        for (COSName name : resources.getXObjectNames()) {
            PDXObject xobject = resources.getXObject(name);
            if (xobject instanceof PDImageXObject) {
                PDImageXObject image = (PDImageXObject) xobject;
                images.add(new float[]{image.getWidth(), image.getHeight()});
            }
        }
    }

    /**
     * 扫描单页内容流，收集算子计数、矩形（{@code re}）与图片绘制矩阵。
     * 图片矩阵取 {@code Do} 前紧邻的 {@code cm} 操作数 {@code [a b c d e f]}，其中 a 为绘制宽度、d 为绘制高度。
     */
    private void collect(PDPage page, Map<String, Integer> operators, List<float[]> boxes,
                         List<float[]> drawMatrices) throws IOException {
        List<COSBase> operands = new ArrayList<>();
        List<COSBase> lastCm = null;
        for (Object token : new PDFStreamParser(page).parse()) {
            if (token instanceof Operator) {
                String name = ((Operator) token).getName();
                operators.merge(name, 1, Integer::sum);
                if ("cm".equals(name)) {
                    lastCm = new ArrayList<>(operands);
                } else {
                    if ("re".equals(name) && operands.size() >= 4) {
                        int size = operands.size();
                        boxes.add(new float[]{operand(operands.get(size - 4)), operand(operands.get(size - 3)),
                                operand(operands.get(size - 2)), operand(operands.get(size - 1))});
                    } else if ("Do".equals(name) && lastCm != null && lastCm.size() >= 6) {
                        drawMatrices.add(new float[]{operand(lastCm.get(0)), operand(lastCm.get(1)),
                                operand(lastCm.get(2)), operand(lastCm.get(3))});
                    }
                    lastCm = null;
                }
                operands.clear();
            } else if (token instanceof COSBase) {
                operands.add((COSBase) token);
            }
        }
    }

    private float operand(COSBase base) {
        return base instanceof COSNumber ? ((COSNumber) base).floatValue() : 0f;
    }

    /** 一段已渲染的文本及其位置（x/y 为元素左上角，y 自上而下增大）。 */
    private static final class Glyph {

        private final String text;
        private final float x;
        private final float y;

        private Glyph(String text, float x, float y) {
            this.text = text;
            this.x = x;
            this.y = y;
        }
    }

    /** 一次渲染的结果：页数、页面尺寸、文本片段、算子计数、矩形外框、嵌入图片与图片绘制矩阵。 */
    private static final class Rendered {

        private final int pages;
        private final float pageWidth;
        private final List<Glyph> glyphs;
        private final Map<String, Integer> operators;
        private final List<float[]> boxes;
        private final List<float[]> images;
        private final List<float[]> drawMatrices;

        private Rendered(int pages, float pageWidth, List<Glyph> glyphs,
                         Map<String, Integer> operators, List<float[]> boxes, List<float[]> images,
                         List<float[]> drawMatrices) {
            this.pages = pages;
            this.pageWidth = pageWidth;
            this.glyphs = glyphs;
            this.operators = operators;
            this.boxes = boxes;
            this.images = images;
            this.drawMatrices = drawMatrices;
        }

        private Glyph glyph(String text) {
            for (Glyph glyph : glyphs) {
                if (glyph.text.equals(text)) {
                    return glyph;
                }
            }
            fail("未在渲染结果中找到文本：" + text + "，实际包含：" + text());
            return null;
        }

        /** 页面上所有文本片段按绘制顺序拼接后的内容。 */
        private String text() {
            StringBuilder builder = new StringBuilder();
            for (Glyph glyph : glyphs) {
                builder.append(glyph.text);
            }
            return builder.toString();
        }

        private int rectCount() {
            return boxes.size();
        }

        private int operatorCount(String name) {
            return operators.getOrDefault(name, 0);
        }

        /** 第 index 个嵌入图片的像素宽度。 */
        private int imageWidth(int index) {
            assertTrue("应至少嵌入 " + (index + 1) + " 张图片，实际为 " + images.size(), images.size() > index);
            return (int) images.get(index)[0];
        }

        /** 第 index 个嵌入图片的像素高度。 */
        private int imageHeight(int index) {
            assertTrue("应至少嵌入 " + (index + 1) + " 张图片，实际为 " + images.size(), images.size() > index);
            return (int) images.get(index)[1];
        }

        /** 第 index 次图片绘制时的矩阵 {@code [绘制宽度, 0, 0, 绘制高度]}。 */
        private float[] drawMatrix(int index) {
            assertTrue("应至少绘制 " + (index + 1) + " 次图片，实际为 " + drawMatrices.size(),
                    drawMatrices.size() > index);
            return drawMatrices.get(index);
        }
    }
}
